#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

if [ ! -x "$(command -v brew)" ]; then
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
	brew update
fi

brew bundle
brew link gettext --force

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
